name: Test


on:
  push:
    branches:
      - main
    workflow_call:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-lastest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use node 16.5.0
      uses: actions/setup-node@v3
      with:
        node-version: '16.5.0'

    - name: Install dependencies
      run: npm ci

    - name: Testing
      run: npm test